# 编译类型
type: maven

# 名称
name: jdbcrest

# 镜像编译参数
docker:
  # 镜像名称
  image: snz1.cn/database/jdbcrest
  # 镜像编译文件(默认：Dockerfile)
  file: Dockerfile
  # 目标平台
  platform:
  - linux/amd64
  - linux/arm64

# 组件发布
helmpush:
  name: snz1dp-nexus

# 服务定义
service:
  # 端口定义
  ports:
  - 9088:80

  # 环境变量
  envs:
  - CONFIG_PROFILE=prod
  - TZ=Asia/Shanghai
  - APP_CODE=jdbcrest
  - DB_POOL_SIZE=3
  - DB_POOL_IDLE=3
  - DB_POOL_MAX=15
  - DB_MAX_WAIT=60000
  - DB_EVICTION_TIME=60000
  - DB_IDLE_TIME=300000
  - DB_TEST_IDLE=true
  - DB_TEST_BORROW=false
  - DB_TEST_RETURN=false
  - CHECK_PROXY_SIGNATURE=false
  - PROXY_SIGNATURE_SALT=
  - SUPPORT_GROUP=
  - SUPPORT_EMAIL=
  - JWT_TOKEN="{{ .Snz1dp.Jwt.Token }}"
  - JWT_PRIVKEY="{{ .Snz1dp.Jwt.PrivateKey }}"
  - CACHE_TYPE=none
  - CONFIG_TYPE=cluster
  - CONFIG_URL="{{ .Confserv.Web.Protocol }}://{{ .Confserv.Web.Host }}:{{ .Confserv.Web.Port }}{{ .Confserv.Web.Webroot }}"
  - XEAI_URL="{{ .Xeai.Web.Protocol }}://{{ .Xeai.Web.Host }}:{{ .Xeai.Web.Port }}{{ .Xeai.Web.Webroot }}"
  - JAVA_OPTS="-Xms128m -Xmx2g -XX:-UseGCOverheadLimit"

  # 心跳检查
  healthcheck:
    url: /jdbc/rest/api/health
    interval: 10s
    timeout: 10s
    period: 30s
    retries: 30

  # 路由定义
  ingress:
  - backend-port: 80
    jwt:
    - /jdbc/rest/api
    anonymous:
    - /jdbc/rest/api/health
    - /jdbc/rest/api/version
    - /jdbc/rest/api/v3
    - /jdbc/rest/api/swagger-ui
    - /jdbc/rest/api/swagger-resources

# 开发配置
develop:
  config: |
    postgres:
      install: true
      host: postgres
      port: 5432
      version: "14.4"
      admin:
        username: postgres
        password: snz1dp9527
    redis:
      host: redis
      install: true
      password: snz1dp9527
      port: 6379
      version: 6.2.5
    confserv:
      install: true
      version: 2.2.1
    appgateway:
      version: 2.8.1-802
      install: true
      admin:
        host: ingress
        port: 91
        protocol: http
    xeai:
      version: 2.6.5
      install: true
    snz1dp:
      admin:
        password: 123456
        username: root
        email: root@localhost.com
      helmrepo:
        url: https://snz1.cn/nexus/repository/helm-hosted
      ingress:
        host: localhost
        port: 80
        protocol: http
      namespace: snz1dp-system
      organization: ChangSha SNZ1
      registry:
        secure: true
        url: gitlab.snz1.cn:9288
      timezone: Asia/Shanghai
      version: 1.1.0-911
