package com.snz1.jdbc.rest.data;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import lombok.Data;

@Data
public class JdbcInsertRequest implements Serializable {
 
  // 表名
  private String table_name;

  // 主键
  private Object primary_key;

  // 输入数据
  private Object input_data;

  // 输入主键
  private String input_key;

  // 字段
  private List<TableColumn> columns;

  // 是否有主键
  public boolean hasPrimary_key() {
    return this.primary_key != null;
  }

  // 是否符合主键
  public boolean testComposite_key() {
    return primary_key instanceof List;
  }

  // 是否子增长ID
  public boolean hasAutoGenerated() {
    for (TableColumn col : columns) {
      if (col.getAuto_increment() != null && col.getAuto_increment()) {
        return true;
      }
    }
    return false;
  }

  // 是单数据
  public boolean testSignletonData() {
    if (this.input_data == null) return true;
    return !(this.input_data instanceof List);
  }

  @SuppressWarnings("unchecked")
  public List<Map<String, Object>> getInputDataList() {
    if (this.getInput_data() instanceof List) {
      return (List<Map<String, Object>>)this.getInput_data();
    } else {
      return Arrays.asList((Map<String, Object>)this.getInput_data());
    }
  }

}
